remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Hosung Kim"
description: "USC Business Analytics • Data Science · AI · ML · DL"
# These create the top nav in the Minimal theme:
# (Make sure these files exist at those paths)
header_pages:
  - projects/index.md
  - about/index.md
  - resume/index.md
  - blog/index.md
  - contact/index.md
